# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pixelant\PxaSocialFeed\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Controller/AdministrationController.php'

  Pixelant\PxaSocialFeed\Controller\AdministrationController:
    public: true